# Generated by Django 3.2.3 on 2021-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/avatar.jpg', upload_to='media/Profile_Images'),
        ),
    ]
