# Generated by Django 3.2.3 on 2021-05-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'verbose_name_plural': 'Product'},
        ),
    ]
