# Generated by Django 3.2.3 on 2021-05-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210520_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oquantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
